class Model:
    def forward_prop(self, x):
        ...

    def back_prop(self, x, y, prediction, loss, learning_rate):
        ...

    def fit(self, x, y, epochs, loss, learning_rate):
        ...

    def predict(self, x):
        ...
